version: "3.0"
services:
  database-mysql:
    image: "mysql:8.0.29"
    restart: "always"
    environment:
      ### You must change root database password
      MYSQL_ROOT_PASSWORD: "db-password"

      # No need to change the following
      MYSQL_DATABASE: "onedev"
    volumes:
      - "./db-data:/var/lib/mysql"
    #ports:
      #- 3306:3306
      #- 0.0.0.0:3306:3306

  onedev:
    image: "1dev/server"
    volumes:
      - "./onedev:/opt/onedev"
    restart: "always"
    ports:
      - "6610:6610"
      - "6611:6611"
    environment:
      ### You must change database connection password, and admin account password:
      hibernate_connection_password: "db-password"
      initial_password: "admin-password"
      ### It is also a good idea to set up initial email, and server URL
      initial_email: "your@email.com"
      # initial_server_url: "https://your.domain.name"

      # No need to change the following
      initial_user: "admin"
      hibernate_dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
      hibernate_connection_driver_class: "com.mysql.cj.jdbc.Driver"
      hibernate_connection_url: "jdbc:mysql://database-mysql:3306/onedev?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&disableMariaDbDriver=true"
      hibernate_connection_username: "root"
